%define		edit_version 0.3
Summary:	Screen Recorder which saves a VNC session as a .swf file
Summary(pl):	Nagrywacz obrazu z ekranu
Name:		vnc2swf
Version:	0.5.0
Release:	1
License:	GPL v2
Group:		X11/Applications
Source0:	http://www.unixuser.org/~euske/vnc2swf/%{name}-%{version}.tar.gz
# Source0-md5:	2eed9cd91cff76e69004c905660b00ae
Source1:	http://www.unixuser.org/~euske/vnc2swf/edit_vnc2swf-%{edit_version}.tar.gz
# Source1-md5:	606ed2294b20f1d2aa198d7d66ce82c3
URL:		http://www.unixuser.org/~euske/vnc2swf/
BuildRequires:	autoconf
BuildRequires:	ming-devel >= 0.3.0
BuildRequires:	XFree86-devel
BuildRequires:	zlib-devel
Requires:	XFree86-tools
Requires:	ming >= 0.3.0
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
Vnc2swf is a screen recording tool. Vnc2swf captures the live motion
of a screen with VNC protocol and generates a Macromedia Flash(TM)
movie (.swf).

%description -l pl
Vnc2swf jest narzêdziem rejestruj±cym obraz z ekranu. Dostêp do
ruchomej zawarto¶ci ekranu odbywa siê za po¶rednictwem protoko³u VNC.
Wynikowy plik jest zapisany w formacie filmu Macromedia Flash (.swf).

%description -l ja
Vnc2Swf ¤Ï VNC ¤òÏ¿²è¤·¤Æ Flash ¤ËÊÑ´¹¤¹¤ë¥×¥í¥°¥é¥à¤Ç¤¹¡£

%package -n edit_vnc2swf
Summary:	Editing Tool for Vnc2swf
Summary(pl):	Narzêdzie do edycji dla Vnc2swf
Group:		Applications
Requires:	python >= 1:2.3
Requires:	python-pygame >= 1.6
Version:	%{edit_version}
URL:		http://www.unixuser.org/~euske/vnc2swf/edit_vnc2swf.html

%description -n edit_vnc2swf
Edit_vnc2swf is an editing tool for vnc2swf. This program allows you
to chop, splice, crop, and attach an MP3 audio to a .swf (ShockWave
Flash) movie generated by vnc2swf. Also this program does some
optimization to reduce the movie size a little bit. From version 0.2,
it supports ScreenVideo format which was newly introduced in Flash
version 7. Generally with this new format a movie can lose the weight
without losing the quality, and it requires much less memory to play
on your browser.

%description -n edit_vnc2swf -l pl
Edit_vnc2swf to narzêdzie do edycji dla vnc2swf. Ten program umo¿liwia
ciêcie, ³±czenie, wycinanie i do³±czanie d¼wiêku MP3 do filmów .swf
(ShockWave Flash) wygenerowanych przez vnc2swf. Ten program wykonuje
tak¿e pewn± optymalizacjê w celu zmniejszenia nieco rozmiaru filmu. Od
wersji 0.2 obs³uguje format ScreenVideo niedawno wprowadzony w wersji
7 Flasha. Zasadniczo przy u¿yciu tego nowego formatu film mo¿e
zmniejszyæ rozmiar bez utraty jako¶ci i wymaga du¿o mniej pamiêci do
odtwarzania w przegl±darce.

%prep
%setup -q -a1
mv edit_vnc2swf-%{edit_version} edit_vnc2swf

%build
%{__autoconf}
%configure
%{__make}

sed -e s@./vnc2swf@vnc2swf@ recordwin.sh > recordwin

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT%{_bindir}

install vnc2swf recordwin $RPM_BUILD_ROOT%{_bindir}
install edit_vnc2swf/edit_mp3.py $RPM_BUILD_ROOT%{_bindir}
install edit_vnc2swf/edit_vnc2swf.py $RPM_BUILD_ROOT%{_bindir}

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%doc docs/vnc2swf.html
%attr(755,root,root) %{_bindir}/vnc2swf
%attr(755,root,root) %{_bindir}/recordwin

%files -n edit_vnc2swf
%defattr(644,root,root,755)
%doc edit_vnc2swf/README.html
%attr(755,root,root) %{_bindir}/edit_*
